# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true

favicon = "favicon.ico"
description = "test"

[footer]
since = 2021
customText = ""

[dateFormat]
published = "2006-01-02"
lastUpdated = "2006-01-02 15:04 MST"

[sidebar]
#emoji = "ğŸ¥"
subtitle = "ãƒ—ãƒ­ã‚°ãƒ©ãƒã®æŠ€è¡“ãƒ–ãƒ­ã‚°ã€‚ãƒ—ãƒ­ã‚°ãƒ©ãƒŸãƒ³ã‚°ã€Vimã€AWSãªã©"

[sidebar.avatar]
enabled = true
local = true
src = "img/avatar.png"

[article]
math = false
readingTime = true

[article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"

## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"

#[opengraph.twitter]
#site = ""
#card = "summary_large_image"
#
#[defaultImage.opengraph]
#enabled = false
#local = false
#src = ""

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = false

[imageProcessing.content]
enabled = false

## Comments
[comments]
enabled = true
provider = "disqus"

[comments.disqusjs]
shortname = "k-s-blog"
#apiUrl = ""
#apiKey = ""
#admin = ""
#adminLabel = ""

